### ISSUE TITLE
CTRL shortcuts don't work on Lightpad

### ISSUE THREAD

**Issue by RootPSWD** [rhino-linux/unicorn#2]
I've already reported this on Discord to oklopfer but I'm making an issue here just in case.

So typing anything with CTRL, like select all, copy, paste, all just reports the unknown character along with the unicode numbers:
![image](https://github.com/rhino-linux/unicorn/assets/126992503/63d392b6-6540-4974-add0-328dc812298f)
This might just be happening because the text box isn't meant to handle those commands, I honestly don't know though.

**Comment by ajstrongdev** [comment]
Please open this issue on the lightpad repository. We have not modified lightpad in such a way that this should not be possible and so the issue lies with lightpad.
