### ISSUE TITLE
BUG: LightDM fails to start properly

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/unicorn#22]
**Describe the bug**
On some systems, lightdm appears to be failing to launch Unicorn properly.

**Expected behavior**
Unicorn launches from LightDM properly.

**Temporary fix:**
We are investigating a cause for this issue. If experiencing this issue, switch to a TTY, and type the following in your terminal:
`sudo systemctl stop lightdm && unicorn-session`

**Comment by ajstrongdev** [comment]
@oklopfer any update?

**Comment by oklopfer** [comment]
It seems like the issue might only exist on NVIDIA laptops @ajstrongdev so...

**Comment by ajstrongdev** [comment]
@oklopfer Right, once users have ran `sudo systemctl stop lightdm && unicorn-session` once does the issue persist, or do they only need to run that command once?

**Comment by oklopfer** [comment]
> @oklopfer Right, once users have ran `sudo systemctl stop lightdm && unicorn-session` once does the issue persist, or do they only need to run that command once?

Remember earlier when I said I was gunna fall asleep but please comment here that the issue is `xserver-xorg-video-vesa xserver-xorg-video-fbdev` being missing, which I should add as unicorn deps

**Comment by pafranklin77** [comment]
Having the same issue with a Lenovo using intel iRISxe graphics.

**Comment by oklopfer** [comment]
> Remember earlier when I said I was gunna fall asleep but please comment here that the issue is `xserver-xorg-video-vesa xserver-xorg-video-fbdev` being missing, which I should add as unicorn deps

Based on https://wiki.ubuntu.com/X/Troubleshooting/VideoDriverDetection, this definitely was the issue. Closing up
