### ISSUE TITLE
BUG: Dropbox folder opens in VS Codium

### ISSUE THREAD

**Issue by TailstheFox92** [rhino-linux/unicorn#28]
**Rhino Linux Version:**
Rhino Linux 2023.1 (mainline) x86_64

**Platform:**
Intel i5-7200U (4) @ 3.100GHz / LENOVO LNVNB161216

**Describe the bug**
Using the dropdown menu in Dropbox on the system tray opens the folder in VSCodium.

**To Reproduce**
1. Right click on Dropbox system tray icon
2. Click on "Open Dropbox Folder"
3. VSCodium Opens

**Expected behavior**
Thunar should open instead, inside of the dropbox folder

**Screenshots**
![vs-dropbox-bug](https://github.com/rhino-linux/unicorn/assets/41931137/a1a51039-f5a6-494a-8909-183e94670458)

**Additional context**
This is with the Flatpak version of Dropbox. I'm not sure if it's the same with the standard version.

**Comment by ajstrongdev** [comment]
This seems to be an issue with where the flatpak version of Dropbox is looking, is there a settings manager? 

This does not appear to be an issue with Rhino Linux, however I will attempt to fix the issue on our Discord where you first brought it to our attention, leaving this open for now.

**Comment by ajstrongdev** [comment]
Closing due to this not being an issue with Rhino Linux
