### ISSUE TITLE
Proposal: Global menus

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/unicorn#31]
We can package and implement https://github.com/rilian-la-te/vala-panel-appmenu to bring a global menu back to Linux by default, similar to the one found in Unity or on macOS

**Comment by oklopfer** [comment]
I think a global menu is an extraordinarily good idea.

**Comment by ajstrongdev** [comment]
Moved to: Todo

**Comment by ajstrongdev** [comment]
Completed
