### ISSUE TITLE
Enh: Trimming Unicorn filesize

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/unicorn#36]
Right now we use the xfce4-goodies package. We really should see and curate a list of actual xfce4-goodies that we utilise, and remove the excess. 

Since xfce4-goodies is a metapackage, we can rather install the packages we use instead of the entire metapackage.

**Comment by oklopfer** [comment]
nope we need all of em, its the smaller choice to installing xfce as a whole, which unicorn does
