### ISSUE TITLE
Feat: Add auto tiling option for windows

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/unicorn#39]
Implement a custom cortile configuration, that @Elsie19 has mocked up to add options for a toggleable auto-tiling option similar to Pop!_Shell found in the earlier versions of Pop!_OS pre-cosmic. 

All features seem to be complete except for autostart and packaging. Will need a discussion from the team about whether this should be implemented before we continue.

**Comment by ajstrongdev** [comment]
@Elsie19 If you can update me on the status, what is left to be done and where all the cortile configuration files are uploaded?

**Comment by Elsie19** [comment]
> @Elsie19 If you can update me on the status, what is left to be done and where all the cortile configuration files are uploaded?

I need to make a pacscript for it. I uploaded the config to you on discord already.

**Comment by ajstrongdev** [comment]
Yep that's fine. Let me know once the cortile pacscript has been created and then I can work with Oren to package the changes into Unicorn @Elsie19

**Comment by ajstrongdev** [comment]
Packaging status update: Cortile pacscript has now been open

What's left?
- [ ] This gets merged.
- [ ] Update Unicorn packaging to place configuration file for cortile in the correct place.
- [ ] Update Unicorn repository to add cortile as an autostart app.

**Comment by oklopfer** [comment]
done
