### ISSUE TITLE
BUG: [Installed apps wont run.  not a snap cgroup]

### ISSUE THREAD

**Issue by CoolGames** [rhino-linux/unicorn#43]
**Rhino Linux Version: 2023.3**

**Platform: Raspberry Pi 400**

**Describe the bug**
I tried to use rhino-pkg install shotwell which succeeded with snap shotwell 32.2 stable but
it would not run with icon and needed a command line invocation that causes warnings while running.

```
$ snap list shotwell
Name      Version  Rev  Tracking       Publisher     Notes
shotwell  0.32.1   8    latest/stable  ken-vandine✪  -
$ snap run shotwell -b
/user.slice/user-1001.slice/session-c1.scope is not a snap cgroup



```
**To Reproduce**
1. Go to 'terminal'
2. `sudo rhino-pkg install shotwell` 
3. Try to use icon and nothing happens
4. Use terminal to do the command before run command
`export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus
`

**Expected behavior**
Application SHOTWELL to run from ICON like other previously installed programs

**Screenshots**
![Snap Shotwell workaround - Screenshot_2023-10-13_10-06-30](https://github.com/rhino-linux/unicorn/assets/149711/e407c3db-f5e4-48d9-b967-ac436d6c702a)

**Additional context**
Problem does not present using Xubuntu login
Even after upgrade to 23.10 issue still occurs

Similar [Bug was reported at snapd 1951491](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1951491) in 2021 
 and showed the attempted workaround

**Comment by ajstrongdev** [comment]
This issue still seems to persist within Snapd, we can see about opening up a line of communication but for the moment I will hazard a guess and say that this seems to be an issue with snapd itself.

Perhaps try the shotwell flatpak? https://flathub.org/en-GB/apps/org.gnome.Shotwell

Leaving open for now.

**Comment by ajstrongdev** [comment]
@CoolGames Have you tried this?
https://github.com/rhino-linux/unicorn/issues/43#issuecomment-1762856004

**Comment by ajstrongdev** [comment]
Consider attempting to install `dbus-user-session` via the apt repositories and trying again: 
https://forum.snapcraft.io/t/cannot-launch-snap-applications-with-cgroup-v2/27700/4

**Comment by CoolGames** [comment]
Moved on to Ubuntu 64 bit so will re-visit in future when I have time.

**Comment by hypeitnow** [comment]
Hi all, 

the only working solution so far sems to be:
```
sudo apt-install dbus-user-session
systemd --user
export DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
```
It works from terminal but how can I move it to start with user session Xubuntu
Where Can one add it in some startup script? 
@ajstrongdev  can you help here? 

Thanks

**Comment by ajstrongdev** [comment]
The Unicorn startup script will need to be modified, therefore I will be transferring this issue to @oklopfer since they were the original creator of that script.

**Comment by oklopfer** [comment]
Should be fixed now after updating from pacstall. (see https://github.com/rhino-linux/unicorn/commit/74d89da74b60dfe402fd8dbe6d69e34497086629 for commit) 

@ajstrongdev we will have to give the live images a good testing after this, though, to make sure initial setup doesn't need anything else from us dropping `dbus-launch`, but I don't think it will.

**Comment by ajstrongdev** [comment]
Duly noted, good work @oklopfer

**Comment by oklopfer** [comment]
can finally confirm it does not break live images, closing
