### ISSUE TITLE
BUG: Screen freeze in VM at random times

### ISSUE THREAD

**Issue by Elsie19** [rhino-linux/unicorn#44]
**Rhino Linux Version:**
2023.3

**Platform:**
x64_64

**Describe the bug**
In Gnome Boxes, or Virtualbox, it just sometimes freezes with no warning or anything.

**To Reproduce**
Install in gnome boxes/virtualbox, use it for a while, wait fore freeze.

**Expected behavior**
No freezing

**Additional context**
@oklopfer said to install `spice-vdagent spice-webdavd xserver-xspice xserver-xorg-video-qxl`.

**Comment by oklopfer** [comment]
@Elsie19 did installing these make any difference or have you not been able to test yet

**Comment by Elsie19** [comment]
I haven't had any freezes since.

**Comment by oklopfer** [comment]
how frequently have you used it in comparison, like do you think you've spent enough time post-installing them to say there is at least definite positive correlation
