### ISSUE TITLE
BUG: cortile on conky 

### ISSUE THREAD

**Issue by oklopfer** [rhino-linux/unicorn#45]
A user in our discord who uses conky on their setup has reported that cortile’s tiling mode breaks with conky, and forces windows to the bottom of the screen where they can’t be seen; starting without conky fixes the issue for them, so we need to figure out how to make it correctly ignored.

**Comment by ajstrongdev** [comment]
Potential fix found in a reddit thread: https://www.reddit.com/r/bspwm/comments/105evwl/how_can_i_make_conky_not_overlap_windows/

In your .conkyrc file:
```
own_window_type = 'desktop'
```
From what i can gather, it will make conky behave more as a desktop widget as it should.

**Comment by oklopfer** [comment]
this was confirmed fixed by the user who reported it initially
