### ISSUE TITLE
BUG: Unicorn desktop environment doesn't shown anymore

### ISSUE THREAD

**Issue by McProgger** [rhino-linux/unicorn#46]
**Rhino Linux Version:**
2023.3

**Platform:**
CPU: dual core Intel Core i7-6500U (-MT MCP-)
Device: HP Laptop

**Describe the bug**
After starting my laptop and log in only a normal XFCE appear (no unicorn specific sidebar, no icon at the start button on the top left, no wallpaper).

**To Reproduce**
1. Open a Terminal
2. Write sudo apt install unicorn-desktop
3. An error message is shown that the package doesn't exist but if I type uni and make a tab unicorn-desktop is shown in the list

**Expected behavior**
After starting rhino linux unicorn should be shown.

**Comment by ajstrongdev** [comment]
Fix: `pacstall -PI linux-kernel-stable ulauncher-deb rhino-core`
