### ISSUE TITLE
BUG: [Cannot change Rhino Linux XFCE's AppMenu items]

### ISSUE THREAD

**Issue by MarioInJapan** [rhino-linux/unicorn#50]
**Rhino Linux Version:**
2023.4

**Platform:**
[AMD]

**Describe the bug**
Even after deleting folders such as Documents, Pictures, Video and the like from the Home directory, they keep showing in the "Desktop  Files Documents Pictures Videos" menu in the panel upon launching Rhino.

**To Reproduce**
1. Launch Rhino
2. From Thunar, delete the Pictures folder (example)
3. Return to the desktop and confirm that the Pictures folder is still shown in the panel

**Expected behavior**
Deleted folders should not appear in the desktop AppMenu bar.

**Additional context**
Furthermore, even if the new folders are added to the Home directory, they do not appear in the desktop AppMenu.

**Comment by ajstrongdev** [comment]
This is a bug with the upstream appmenu plugin that we utilise.
