### ISSUE TITLE
BUG: [SEARCHBAR SCRAMBLES ICONS ON REBOOT]

### ISSUE THREAD

**Issue by mike3764** [rhino-linux/unicorn#52]
**Rhino Linux Version:**
 OS: Rhino Linux 2023.4 (mainline) x86_64 
 Host: ASRock Z390 Pro4 
Kernel: 6.7.0-060700-generic 

**Platform:**
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  12
  On-line CPU(s) list:   0-11
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    CPU family:          6
    Model:               158
    Thread(s) per core:  2
    Core(s) per socket:  6
    Socket(s):           1
    Stepping:            10
    CPU(s) scaling MHz:  17%
    CPU max MHz:         4600.0000
    CPU min MHz:         800.0000
    BogoMIPS:            6399.96

**Describe the bug**
Each time I reboot, the searchbar scrambles the icons placed on it, despite the icons being locked in the preferences.

**To Reproduce**
reboot and start up Rhino Linux

**Expected behavior**
I expect the order I place the icons and lock them to be preserved when I reboot  so I don't have to reorganize my searchbar each time I turn on the computer.

**Screenshots**

**Additional context**

**Comment by ajstrongdev** [comment]
Unfortunately i'm going to need some screenshots to have a more clear understanding of the issue.

**Comment by oklopfer** [comment]
> Unfortunately i'm going to need some screenshots to have a more clear understanding of the issue.

I know exactly what the issue is, it's with plank config being a hard file for unicorn. 

To modify your plank config, edit `~/.config/docks.ini` with the changes you want.
