### ISSUE TITLE
Can't upgrade unicorn-desktop, seems that papirus-folders is not installable.

### ISSUE THREAD

**Issue by madnoh** [rhino-linux/unicorn#53]
OS: Ubuntu Noble Numbat (development branch) x86_64 
Host: LENOVO 20FCS27J00 
Kernel: 6.7.1-060701-generic 
Uptime: 2 hours, 30 mins 
Packages: 2284 (dpkg), 24 (pacstall), 21 (flatpak), 11 ( 
Shell: bash 5.2.21 
Resolution: 1920x1080 
DE: Unicorn 
WM: Xfwm4 
WM Theme: Yaru-dark 
Theme: Greybird-dark [GTK3] 
Icons: elementary-xfce-dark [GTK3] 
Terminal: xfce4-terminal 
Terminal Font: Fira Code weight 
CPU: Intel i5-6300U (4) @ 3.000GHz 
GPU: Intel Skylake GT2 [HD Graphics 520] 
Memory: 3678MiB / 7799MiB 

Describe the bug
I can't do updates or install packages beacuse installation of **unicorn-desktop** failed.

To Reproduce
In terminal, I tried `rpk update -y` or `rpk cleanup` or `sudo apt autoremove` it will run to the same error saying papirus-folders is not installable.
Running `pacstall -I unicorn-desktop-git` also doesn't work, the same error saying it depends on papirus-folders but it is not installable.

Expected behavior
I was expecting a smooth update & upgrade process. :-)

Screenshots  
1.
Package:                              Version:                                                             Size:  
unicorn-desktop                    0.0.1-pacstall1~git2f5f17ed                              30.5 MB  

2.
sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... failed.
The following packages have unmet dependencies.
 unicorn-desktop : Depends: papirus-folders but it is not installable
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
E: Unable to correct dependencies

3.
Contents of /var/log/nala/dpkg-debug.log

Apt Do Install

Raw = False: [b'Setting up unicorn-desktop (0.0.1-pacstall1~git2f5f17ed) ...\r\n']

Raw = False: [b"papirus-folders: Changing color of folders to 'violet' for 'Papirus-Dark' ...\r\n"]

Raw = False: [b'\x1b[0;1;31mFailed to connect to bus: No medium found\x1b[0m\r\r\n']

Raw = False: [b'dpkg: error processing package unicorn-desktop (--configure):\r\n installed unicorn-desktop package post-installation script subprocess returned error exit status 1\r\n']

Data_Split = [b'dpkg: error processing package unicorn-desktop (--configure):', b' installed unicorn-desktop package post-installation script subprocess returned error exit status 1']
Raw = False: [b'Errors were encountered while processing:\r\n unicorn-desktop\r\n']

Data_Split = [b'Errors were encountered while processing:', b' unicorn-desktop']
['Traceback (most recent call last):\n', '  File "/usr/lib/python3/dist-packages/nala/dpkg.py", line 461, in run_install\n    os._exit(apt.do_install(self.write_stream.fileno()))  # type: ignore[attr-defined]\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', 'apt_pkg.Error: E:Sub-process /usr/bin/dpkg returned an error code (1)\n']

Any help would be great. Thanks in advance.

**Comment by oklopfer** [comment]
so sorry for the late reply. The following will fix your situation:
`sudo rm /var/lib/dpkg/info/unicorn-desktop* && pacstall -PI unicorn-desktop-git`
