### ISSUE TITLE
Install theme in xubuntu

### ISSUE THREAD

**Issue by laguill** [rhino-linux/unicorn#55]
Hello sorry if my request is not appropriate.

I am currently using xubuntu and I would to know if it possible to use install this theme on my laptop ?
If yes how would it be possible ?

Thanks for your support.

**Comment by ajstrongdev** [comment]
It may be possible via Pacstall. Information on how to set up and then install `unicorn-desktop-git` however since it depends on recent dependencies, it may break at some point as it's assuming you've got a rolling package repository.
